# Generated by Django 2.0.2 on 2018-04-16 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor_child', models.TextField()),
                ('photo_child', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'ChildInfo',
            },
        ),
        migrations.CreateModel(
            name='DadInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor_dad', models.TextField()),
                ('photo_dad', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'DadInfo',
            },
        ),
        migrations.CreateModel(
            name='MomInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor_mom', models.TextField()),
                ('photo_mom', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'MomInfo',
            },
        ),
        migrations.AddField(
            model_name='childinfo',
            name='dad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='faceRecog.DadInfo'),
        ),
        migrations.AddField(
            model_name='childinfo',
            name='mom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='faceRecog.MomInfo'),
        ),
    ]
